### ISSUE TITLE
Write bot to run test of scraper function

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-scrapers#22]
### Feature Description

_A clear and concise description of the feature you're requesting._

A github action that is triggered when on of the maintainers comments: `/test-scraper get_{municipality_slug_name}_events --from_dt={datetime_in_iso} --to_dt={datetime_in_iso}`.

It then runs and returns the data pretty printed as JSON for us to check.

### Use Case

_Please provide a use case to help us understand your request in context._

When someone submits a PR to this repo, we should be able to quickly see what data is returned from the new scraper function. If everything looks okay we move along with the PR.

### Solution

_Please describe your ideal solution._

See Feature Description

### Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them._

**Comment by dphoria** [comment]
I started on this a few days ago. Being my first adventure into github action `yaml` it's taking me some time, true to my MO. 😅 Obviously we have plenty of examples in CDP and the documentation on github actions are pretty neat, it seems. Anyway, I know we are in a crunch for release. Is it OK for me to continue, or shall I give up so someone else can tackle this more quickly?

**Comment by JacksonMaxfield** [comment]
Oh no worries on rush to release. I consider this a like 3.0.1 feature. We should have it before someone _besides_ us wants to commit to CDP-scrapers

**Comment by dphoria** [comment]
Finally, have something working in https://github.com/dphoria/cdp-scrapers/blob/20ec1ceb593d825568ef71bf5c6a3d23ea68c10f/.github/workflows/test-scraper.yml and https://github.com/dphoria/cdp-scrapers/blob/20ec1ceb593d825568ef71bf5c6a3d23ea68c10f/.github/workflows/scripts/run-scraper.py . Works in Issue for sure. Works in PR but I THINK it's not checking out the merge HEAD?

Since `ref` isn't specified for `actions/checkout`, it should check out the PR merge when triggered from PR comment. Not sure it is. Need to verify/resolve that bit. That's all for today.

**Comment by JacksonMaxfield** [comment]
Looks like the object posting size may be too large. We may want to dump the return to an "artifact" instead: https://github.com/actions/upload-artifact and just comment that the run completed and for the user to check the artifacts

**Comment by dphoria** [comment]
Yeah I see it got the events then errored when trying to post as comment. So you are probably right on.
