### ISSUE TITLE
Determine why multi-session event wasn't picked up (Seattle)

### ISSUE THREAD

**Issue by JacksonMaxfield** [CouncilDataProject/cdp-scrapers#38]
https://councildataproject.org/seattle-staging/#/events/0a6849cdbe93

Minutes Items reference multi-session but the only session for the event in our system is actually the second session of the day.

Need to debug and fix multi-session events.

**Comment by dphoria** [comment]
At some point in the past few months, Seattle Legistar changed the video links on the meeting detail page such that it now links to a generic video list for that group, e.g. the budget committee.

For this particular example, the video link on the [meeting detail page](https://seattle.legistar.com/MeetingDetail.aspx?ID=893273&GUID=7AC8D4B3-B2C2-4C11-B4CC-4EF34EE97F2D) is just https://www.seattlechannel.org/BudgetCommittee?Mode2=Video. So the main video on this web page is the most recent one for this committee, NOT the correct one for the particular event from 10/01. Hence, the scraper parses URI for the "wrong" video, which in this case has just 1 video, and thus we end up getting 1 session instead of 2.

Have verified on archive.org that the meeting detail pages used to link to the given event's video. I mean, otherwise the scraper would not have worked back then.

For now I think the only solution is to figure out what the query is when you click on "Filter" on seattlechannel.org video list web page. Then parse the response to find the correct video(s) using event time, etc. I don't like it since we are not using some specific identifier. In the end we need `videoid` for seattlechannel.org, and at least so far I don't see a way to get it from Legistar API returned data, or seattle.legistar.com. Continuing to look.

**Comment by dphoria** [comment]
Interesting... literally 3 meetings from 09/29, 09/30, 10/01 are the only ones without specific seattlechannel.org `videoid` in the video links hahaha. I... don't know why? Meetings before and after these have proper links with `videoid`.

Above comment about detecting anomaly obviously still stands. And I will continue to see alternative ways to get correct meeting videos.

**Comment by dphoria** [comment]
My theory did not have enough data points apparently :sweat_smile: . Opened https://seattle.legistar.com/Calendar.aspx again today, now I see that they have decided to (or always have) use the generic video list URL (e.g. http://www.seattlechannel.org/BudgetCommittee?Mode2=Video) withOUT `videoid` for meetings with multiples sessions. Meetings from 10/13-15 use the non-specific URLs for the "Video" buttons and they all have multiple sessions, like the multi-session one from 10/01 given in the original post.

So now I actually feel better knowing that this is a recognizable pattern. Do something like: get video URIs slightly differently if on web page at ["EventInSiteURL"](https://seattle.legistar.com/MeetingDetail.aspx?ID=893273&GUID=7AC8D4B3-B2C2-4C11-B4CC-4EF34EE97F2D&Options=info|&Search=) I find 1) URL to seattlechannel.org without `videoid` and 2) I find "session i ... session ii" or something similar for "meeting location".

I still quite like the idea to raise error when after all this, I still end up on video web page that does not match the corresponding meeting.

**Comment by JacksonMaxfield** [comment]
> My theory did not have enough data points apparently sweat_smile .

Adding a thought, the past week of meetings has been a ton of multi-session meetings because its budget season. I wonder if they link to the list of videos when it's multi session and link to a specific video when it is single session....

**Comment by JacksonMaxfield** [comment]
Yea.... from a quick look I would say that is the pattern.

**Comment by dphoria** [comment]
100% agreed. Patterns are good! Exceptions not so much haha.

**Comment by dphoria** [comment]
> I just realized that that is exactly what you said. I think I skimmed your response, made the connection but then was like "OOOOOOHHHHH what if". My bad. Nice find joy

No no all good! We are in agreement and yes joy indeed.
