### ISSUE TITLE
Use clean-text

### ISSUE THREAD

**Issue by dphoria** [CouncilDataProject/cdp-scrapers#88]
### Feature Description

`scraper_utils.str_simplified()` was implemented to clean up scraped text. There is a package [clean-text](https://pypi.org/project/clean-text/) that is specialized for exactly that purpose.

### Use Case

Use `clean-text` to clean up text. e.g., Remove repetitive whitespace.

### Solution

Remove `scraper_utils.str_simplified()`. Replace call sites `str_simplified(text)` with something like `cleantext.clean(text, ...)`. Be sure to look at documentation and set arguments as appropriate.

### Alternatives

Check if there is another package that may be better to use instead of `clean-text`.

**Comment by Shak2000** [comment]
Hi @dphoria and @JacksonMaxfield! I would like to take on this issue.

**Comment by Shak2000** [comment]
I researched the package `clean-text` and the function `str-simplified`.

I wrote unit tests to validate that both work the same. The only thing I don't know how to test `input_str = input_str.encode("utf-8").decode("utf-8")` since it seems to me that it is just reversing the operations. Do you have any example for me to test it?

**Comment by dphoria** [comment]
Hm Shak I think you are right; I think that line may not be doing anything. I thought that line would clean up text like "M. Lorena Gonz\u00e1lez". But of course that IS already "clean". i.e.

```Python
input_str = "M. Lorena Gonz\u00e1lez"
input_str
# M. Lorena González
"M. Lorena Gonz\u00e1lez" == "M. Lorena González"
# True
```
I think I was just too tried when I wrote that line hahaha. So, there is no specific test case for that line specifically. Still, would be nice to include text like "M. Lorena Gonz\u00e1lez" in testing `clean-text`.

**Comment by JacksonMaxfield** [comment]
Please do not remove that line. I don't remember what it was doing but I remember Isaac and I added it for a reason.... Something to do with the response of certain pages or content returning in ascii even though it was supposed to be in utf-8.

**Comment by JacksonMaxfield** [comment]
Here was the original PR: https://github.com/CouncilDataProject/cdp-scrapers/pull/21

The comment itself somewhat explains it a bit... basically encode ascii content to utf-8 and then decode it again back to a normal str. Basically just forcing everything in our system to act like utf-8

**Comment by dphoria** [comment]
Ah I see. That's true Shak; we all know how ill formed scraped data can be.

**Comment by Shak2000** [comment]
I intentionally did not yet replace `str_simplified` in `scraper_utils.py`. Instead, I created a new function called `str_simplified_new` in addition to creating unit tests. Once you review my changes, I will remove `str_simplified` and rename `str_simplified_new` into `str_simplified`.

I chose to make this incremental change because there are many places in the code that use `str_simplified`, and I did not want to disrupt them.

**Comment by Shak2000** [comment]
Do you have any feedback regarding the PR? If there is no feedback, I would change `str_simplified_new` into `str_simplified` and remove the old `str_simplified`.

**Comment by dphoria** [comment]
I already reviewed/accepted it Shak. https://github.com/CouncilDataProject/cdp-scrapers/pull/97#pullrequestreview-980839633

**Comment by Shak2000** [comment]
Thanks! I removed the `str_simplified_new` function.
